version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - redis
    links:
      - postgres
  redis:
    image: redis
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=places
    ports:
      - "5432:5432"
